name: line message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_ROOM_ID: ${{ secrets.LINE_ROOM_ID }}
        CUSTOM_SCRIPT: |
          curl -v -X POST https://api.line.me/v2/bot/message/push \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${LINE_CHANNEL_ACCESS_TOKEN}' \
          -d '{
              "to": "${LINE_ROOM_ID}",
              "messages":[
                  {
                      "type":"text",
                      "text":"test :)"
                  }
              ]
          }'
      
      
   
