name: line message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ufoo68/line-push-message@v1.4
      with:
        user-id: ${{ secrets.LINE_ROOM_ID }}
        message: 'test'
        channel-access-token: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}t.
