name: line message
on: [push]
jobs:
  mac:
    name: on latest mac
    runs-on: macos-latest
    steps:
    - run: |
        brew install coreutils
        dir=$(dirname $(grealpath $(which pod)))
        if [ `uname -m` = "arm64" ]; then
          dir=$(grealpath $dir/../libexec/gems)
        else
          dir=$(grealpath $dir/../gems)
        fi
        echo $dir
        f=$(grep --include=\*.rb -rnwl $dir -e "unless lib_name.end_with?('.a')")
        sed -i '' "s/unless lib_name.end_with?('.a') && lib_name.start_with?('lib')/unless (lib_name.end_with?('.a') || lib_name.end_with?('.dylib')) \&\& File.basename(lib_name).start_with?('lib')/g" $f
        f=$(grep --include=\*.rb -rnwl $dir -e "validate_nonempty_patterns(attr_name, :error)")
        sed -i '' "s/validate_nonempty_patterns(attr_name, :error)/(attr_name.to_s == 'vendored_libraries') || validate_nonempty_patterns(attr_name, :error)/g" $f
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_TO: ${{ secrets.LINE_ROOM_ID }}
