name: line message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/line-action@master
      with:
        #secret: ${{ secrets.LINE_CHANNEL_SECRET }}
        token: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        room: ${{ secrets.LINE_ROOM_ID }}
        args: line message from GitHub Actions ${{ github.event_name }} event.
